### ISSUE TITLE
Upwork Posting

### ISSUE THREAD

**Issue by stefan-ptrvch** [BeamNG/zoe#1]
Hi @tdev!

The Upwork job posting for this project hasn't been checked in a while, so I just wanted to ask whether it's still open or not.
Hope this isn't inappropriate! The project seems super interesting!

**Comment by tdev** [comment]
yes, its still open, just incredibly busy with work

**Comment by th37rose** [comment]
@tdev This is opened job to contribute on?
I was released from RisingBrain - https://github.com/ttt246/Brain
And I am looking for a new role. When I was working at that project, I've worked as a project manger and worked as a first employee so that I'd created the skeleton of the project in the beginning. 

I am looking forward to hearing you. 
Best,

**Comment by pongzu313** [comment]
@tdev As a python developer, I am very interested in the position. I am proficient in not only python but devops engeering and AI industry. Would like to talk with you.

You can check out my linkedin. [https://www.linkedin.com/in/peter-newman-68693a2bb]

Best.

**Comment by TP817** [comment]
Hi Thomas F, I am very interested in joining the project as a member of the team.
I have rich experience in mobile apps and backend development, specialized in cross-platform frameworks(Flutter, RN) and native frameworks like Swift, Kotlin and so on. Hope to continue the discussion. 😉  Warm Regards.

**Comment by golden1831** [comment]
Hi @tdev, really exciting to taking with you about this particular opportunity.
I am a senior software engineer who is very familiar with backend & frontend both with Python & Django & FastAPI and also modern Javascript libraries like Angular and Vue.js as well.

Let's discuss further about this exciting role. Looking forward to hearing from you.
Thank you.

**Comment by tdev** [comment]
Please apply via upwork: https://www.upwork.com/freelance-jobs/apply/Python-game-testing-framework_~017a69cebe94cd6e23/

Thank you!

**Comment by th37rose** [comment]
Thanks, but I don't have it. If you would want my services, you can ping me a message at any time. 
Or we can make a schedule to have a call between us. Thanks again.

**Comment by tdev** [comment]
The project page is now up, please apply with the instructions there: https://coda.io/@tdev/projects/testing-framework-3
